### ISSUE TITLE
Slider function e css

### ISSUE THREAD

**Issue by diegorojas** [brainwp/estudio-elastico-loja-theme#1]
@matheusgimenez transformar o Slider da Home da loja em randômico, diminuir um pouco a altura dele e aumentar o margin-bottom em relação aos itens abaixo dele.

**Comment by matheusgimenez** [comment]
Quanto a deixar ele random, isso vai ser um problema.. já que o slider não é query.. veja os arquivos do slider do mrtailor:

https://gist.github.com/matheusgimenez/6363aa335aa331b501c1

**Comment by diegorojas** [comment]
Certo, que tipo de alterações podemos fazer de forma mais fácil? Pode chamar os mais recentes ou os mais acessados, algo assim?

**Comment by matheusgimenez** [comment]
Ele é um metabox cara, não tem uma forma fácil.. o unico jeito seria refazer por wp_query. Mas seria meio chatinho.. já que ele tem vários arquivos de template e ainda nem consegui saber qual deles o woocommerce ta chamando '-'

**Comment by diegorojas** [comment]
ixe, então calma. Deixa eu estudar ele melhor, testar e tento dar uma idéia. Vai para outras coisas.

**Comment by matheusgimenez** [comment]
Já tive uma ideia... vou fazer aqui e já explico ok?

Mas vai funcionar do jeito que quer mesmo.

**Comment by diegorojas** [comment]
Vai na fé e pé na tabua meu.

**Comment by matheusgimenez** [comment]
Eu copiei parte do codigo e criei um page template novo.. ai é só setar ele como home

**Comment by everaldomatias** [comment]
@matheusgimenez estou finalizando esse projeto (Estúdio Elástico).
Essa issue foi feita pelo que entendi, ela já está em produção?

**Comment by diegorojas** [comment]
opa, da licença.. desculpa a falta de alinhamento eve, mas isso aqui foi feito tá até no beta, mas não implementei ainda e não testei, por isso a issue está aberta, blza?
