### ISSUE TITLE
tornar as 3 colunas da loja em 4

### ISSUE THREAD

**Issue by diegorojas** [brainwp/estudio-elastico-loja-theme#2]
@matheusgimenez tornar as 3 colunas de produtos da loja em 4 colunas de produtos

**Comment by diegorojas** [comment]
Só para ilustrar o que estou vendo agora online com 3 colunas e que devem virar 4. Já vi que precisa aumentar o margin-bottom do botão promoção tb :)

![3-colunas](https://cloud.githubusercontent.com/assets/3632627/5266817/50134b9a-7a33-11e4-95fe-e573584b40da.png)

**Comment by matheusgimenez** [comment]
Feito!

**Comment by diegorojas** [comment]
blza! Onde eu visualizo o tema da loja?

**Comment by matheusgimenez** [comment]
http://wp.codeispoetry.info/lojaelastico/loja/

**Comment by diegorojas** [comment]
Uepa! valeu!

**Comment by everaldomatias** [comment]
@matheusgimenez pelo que alterou nessa issue foi apenas o style. Subi isso em produção mas não funcionou. Tem outra configuração?

**Comment by matheusgimenez** [comment]
Sim, foi só css

**Comment by everaldomatias** [comment]
Veja lá na produção como ficou.

**Comment by everaldomatias** [comment]
Resolved.
