### ISSUE TITLE
Página de Contatos - Adequar Template

### ISSUE THREAD

**Issue by everaldomatias** [brainwp/estudio-elastico-loja-theme#5]
Gostaria de aplicar isso na Loja, aproximar o máximo do template. Modelo http://themeforest.net/item/mr-tailor-responsive-woocommerce-theme/full_screen_preview/7292110

**Comment by everaldomatias** [comment]
@diegorojas me ajuda com isso por favor, quebrei a cabeça aqui mas não consegui:

Demo: http://themeforest.net/item/mr-tailor-responsive-woocommerce-theme/full_screen_preview/7292110

Onde aplicar: http://loja.estudioelastico.com.br/fale-conosco/

Infos para utilizar: http://estudioelastico.com.br/contato/

**Comment by diegorojas** [comment]
Eve, 

Suponho duas coisas:
- que na customização do tema alguma área esteja com display:none por algum outro template e acabou escorregando para esse
- Outra seria que de fato têm muita opção e precisa achar a exata que a Demo está usando...

**Comment by everaldomatias** [comment]
Sim cara, disso estou ligado.

As páginas são feitas com Visual Composer, ontem dediquei algumas horas tentando mas não consegui encontrar nem mesmo o form.

**Comment by diegorojas** [comment]
Eu não acho que isso ai é visual composer man. Acho que é um template do tema mesmo.. Dá uma olhada.

**Comment by everaldomatias** [comment]
Sim cara, disso estou ligado e apliquei o template Contact Us e nada, ele abriu apenas a opção do mapa.

**Comment by diegorojas** [comment]
Putz.. Então deixa para o espetéculo ao vivo! :)
